language: java
sudo: false
jdk:
  - oraclejdk8

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - git clone --depth 1 https://github.com/vitruv-tools/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/setup.sh
install: true

script: mvn clean verify

after_script:
- chmod a+x /tmp/BuildUtilities/travis-ci/deployNightly.sh
- . /tmp/BuildUtilities/travis-ci/deployNightly.sh