<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cipm.consistency</groupId>
		<artifactId>bundles</artifactId>
		<version>0.2.0-SNAPSHOT</version>
	</parent>
	<artifactId>vitruv-3.0.0-cipm</artifactId>
	<packaging>pom</packaging>
	<name>Vitruv 3.0.0 for CIPM</name>

	<profiles>
		<profile>
			<id>run-one</id>
			<modules>
				<module>releng</module>
				<module>bundles</module>
			</modules>
		</profile>
	</profiles>

</project>